OPENAI_API_KEY = ""

LOCAL_COURSE_DIRECTORY_XLSX = "MySkillsFutureCourseDirectory.xlsx"
LOCAL_COURSE_RUN_XLSX = "MySkillsFutureCourseRun.xlsx"

COURSE_DB_PATH = "skillsfuture_courses.sqlite3"
CAREER_ROLES_SEED_PATH = "data/career_roles.json"
COURSE_EMBEDDINGS_PATH = "course_embeddings.npz"

EXTENSION_ID = ""
ALLOW_LOCAL_DEVELOPMENT_ORIGINS = True
API_ACCESS_TOKEN = ""
MAX_REQUEST_BODY_BYTES = 128000
API_REQUEST_TIMEOUT_SECONDS = 45
OPENAI_TIMEOUT_SECONDS = 30
OPENAI_MAX_RETRIES = 1
JOB_ANALYSIS_CACHE_TTL_SECONDS = 900
JOB_ANALYSIS_CACHE_MAX_SIZE = 128
QUERY_EMBEDDING_CACHE_TTL_SECONDS = 1800
QUERY_EMBEDDING_CACHE_MAX_SIZE = 256
RATE_LIMIT_REQUESTS = 30
RATE_LIMIT_WINDOW_SECONDS = 60
